on: 
    push:
        branches:
        - main

jobs:
  build-and-deploy:
    name: Build and Deploy Function App
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Build Function App
      shell: bash
      run: |
        pushd './src/DevOidc/DevOidc.Functions'
        dotnet build --configuration Debug --output ./output
        popd
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Hack for next step (set runtime to None)
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az webapp config appsettings set -g DevOIDC -n devoidc --settings FUNCTIONS_WORKER_RUNTIME=None
    - name: Publish Function App
      uses: Azure/functions-action@v1.3.1
      with:
        app-name: devoidc
        package: ./src/DevOidc/DevOidc.Functions/output
    - name: Update Function App (set runtime to dotnet-isolated & .net version to v5.0)
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az webapp config set -g DevOIDC -n devoidc --net-framework-version v5.0 
          az webapp config appsettings set -g DevOIDC -n devoidc --settings FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
