on: 
    push:
        branches:
        - main
        - dotnet5functions

env:
  AZURE_FUNCTIONAPP_PATH: 'src/DevOidc/DevOidc.Functions'
  AZURE_FUNCTIONAPP_NAME: DevOIDC

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100'
    - name: Resolve Project Dependencies Using Dotnet
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PATH }}'
        dotnet build --configuration Release --output ./output
        dir -r
        popd
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Publish FA
      uses: azure/CLI@v1
      with:
        inlineScript: |
          sudo apt-get update
          sudo apt-get install azure-functions-core-tools-3
          pushd './${{ env.AZURE_FUNCTIONAPP_PATH }}/output'
          func azure functionapp publish devoidc --force 
          az webapp config set -g DevOIDC -n devoidc --net-framework-version v5.0 
          az webapp config appsettings set -g DevOIDC -n devoidc --settings FUNCTIONS_WORKER_RUNTIME=dotnet-isolated
